server:
# 可以直接访问eureka的微服务，其中会有默认界面，显示注册的服务。
#  当前项目访问地址就是：http：//localhost:7000/
  port: 7000

eureka:
  instance:
    #配置当前eureka服务主机地址
    hostname: localhost
  client:
    # 自己就是注册中心，所以不需要“从注册中心取回信息”
    fetchRegistry: false
    
    # 自己就是注册中心，所以自己不注册自己
    register-with-eureka: false
    
    # 客户端访问Eureka 时使用的地址，${eureka.instance.hostname}获取当前配置文件中的信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
      