#--------------springboot集成mybatsi相关配置-----------------------
#springboot集成mybatis步骤3：配置mysql数据库的信息
#注意：这里的键名，不能进行自定义，因为springboot已经指定，自定以不会识别
#可以键名可以再自动配置类包下的配置文件查询配置，也可以查询springboot官方文档
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: yanruyi
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#---------------------springboot集成redis配置-------------------------------
  redis:
#    host: 127.0.0.1
    port: 6000
    password: erziwoshiniba
    timeout: 1800000
  profiles:
    active: dev
#---------------------springboot集成redis配置-------------------------------
#spring集成Mybatis环境
mybatis:
#  #加载Mybatis映射文件
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
#  别名扫描包,配置别名
  type-aliases-package: mybatis.redis.domain
#---------------------springboot集成mybatsi相关配置-----------------------

#服务器相关配置
server:
  port: 8000
  servlet:
    context-path: /mybatis-redis
# 日志相关配置
logging:
  level:
    mybatis.redis: debug